In [2]:
import pandas as pd

In [25]:
# load data
origin = pd.read_csv('Lab02/data.csv')
data = origin[['Platform', 'Genre', "NA_Sales"]] 
data.head()

  Platform         Genre  NA_Sales
0      Wii        Sports     41.36
1      NES      Platform     29.08
2      Wii        Racing     15.68
3      Wii        Sports     15.61
4       GB  Role-Playing     11.27

In [26]:
# focus on the top 10 Platform
data = data[data['Platform'].isin(list(data['Platform'].value_counts()[:10].keys()))].reset_index(drop=True)
data.head()

  Platform     Genre  NA_Sales
0      Wii    Sports     41.36
1      Wii    Racing     15.68
2      Wii    Sports     15.61
3       DS  Platform     11.28
4      Wii      Misc     13.96

In [30]:
#data.set_index('Platform').groupby('Genre').mean()
bertifier_df = data.pivot_table(index='Genre', columns='Platform', values='NA_Sales', aggfunc='mean')
bertifier_df

Platform,DS,GBA,PC,PS,PS2,PS3,PSP,Wii,X360,XB
Genre,,,,,,,,,,
Action,0.191176,0.222335,0.059706,0.400510,0.367299,0.319658,0.107523,0.287215,0.438576,0.221548
Adventure,0.104076,0.242368,0.027077,0.123333,0.034235,0.118784,0.007981,0.130843,0.175833,0.085385
Fighting,0.069167,0.126087,0.016667,0.315648,0.299867,0.314211,0.116892,0.305476,0.378615,0.208542
Misc,0.137673,0.224000,0.237083,0.273158,0.183468,0.181440,0.050000,0.424357,0.501260,0.156304
Platform,0.405604,0.322606,0.004545,0.534531,0.365049,0.360541,0.221944,0.814310,0.243600,0.134286
Puzzle,0.146992,0.179512,0.003600,0.165313,0.157778,0.130000,0.064773,0.165455,0.088571,0.045714
Racing,0.306567,0.183281,0.007213,0.354690,0.350556,0.259674,0.237778,0.332796,0.318269,0.174634
Role-Playing,0.230700,0.387534,0.166827,0.213711,0.175668,0.251513,0.059688,0.156571,0.596667,0.430000
Shooter,0.153810,0.058750,0.125400,0.220417,0.359563,0.525833,0.277297,0.280308,0.859655,0.349697
Simulation,0.238345,0.200556,0.167333,0.113167,0.215222,0.138710,0.067857,0.267816,0.212750,0.226250
Sports,0.104595,0.117045,0.007600,0.288378,0.335300,0.284626,0.130896,0.575846,0.414839,0.241294
Strategy,0.109747,0.233889,0.104415,0.093662,0.050282,0.078333,0.044500,0.092800,0.232143,0.097619

In [33]:
bertifier_df.to_csv('bertifier_df.csv')